[package]
name = "socrates-errors"
version = "0.1.0"
authors = ["Magnus Hallin <mhallin@fastmail.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4", features = ["release_max_level_warn"] }
eyre = "0.6.5"
colored = "2.0.0"