# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  containers:
    - container: rust-1.29.0
      image: rust:1.29.0-slim

jobs:
  - job: Linux

    pool:
      vmImage: 'Ubuntu 16.04'

    container: rust-1.29.0

    steps:
    - script: ./ci/build_and_test.sh
      displayName: Build and test

  - job: macOS
    pool:
      vmImage: xcode9-macos10.13

    steps:
    - script: curl https://sh.rustup.rs -sSf | sh
      displayName: Install Rust

    - script: ./ci/build_and_test.sh
      displayName: Build and test
